# `004` Tensors

Requirements: none.

A tensor is a mathematical structure with an arbitrary number of dimensions. This abstraction can represent many different typical supports:
* A zero-dimensional tensor is a scalar; e.g. `4` is a 0-d tensor.
* A one-dimensional tensor is a vector; e.g. `[0, 1, 2]` is a 1-d tensor.
* A two-dimensional tensor is a matrix
* A three-dimensional tensor can be thought as a 3d volume or a matrix where each component is a vector.
* A four-dimensional tensor can be thought as a matrix in which each component is another vector, or a volume in which each component is a vector, and so on.

In [1]:
import torch

a = torch.tensor([1, 2, 3, 4])
print(a)
a.shape

tensor([1, 2, 3, 4])


torch.Size([4])

The shape of a tensor indicates the dimensionality of each dimension. This sounds like a tonguetwister, but it's actually simple. Each of the dimensions (or axes) of a tensor can have a certain size, and that size is called its dimensionality.

In [2]:

b = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(b)
b.shape

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Size([2, 3])

We can access elements in a tensor using squared bracket notation.

In [3]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a)
print(a[0])
print(a[0, 0])
print(a[:, 0])

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3])
tensor(1)
tensor([1, 4])


All the operations available in normal maths are also implemented for tensors. For instance, we can take two vectors and add or multiply them.

In [4]:
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([2, 2, 2, 2])
print(a * b)
print(a + b)

tensor([2, 4, 6, 8])
tensor([3, 4, 5, 6])


We can also operate with tensors with different dimensions, like one 2 x 3 matrix and one 3-sized vector.

When this happens, the following rule is applied:
* First, dimensions are right aligned, and the missing ones become 1. Since our matrix has shape (2, 3) and two dimensions, our vector will become (1, 3).
* Then, dimensions of the same size are left normally, but dimensions with different size 1 are **broadcast**, or repeated. That makes our vector be repeated twice row-wise into a matrix.
* Finally, the operation is performed.

In some cases, this process will try to match two dimensions in which one of them is not 1 or the same as the other operator. In these cases we will get an error.

In [7]:
a = torch.randn(1, 2, 3)
b = torch.ones(2, 3)
c = torch.ones(1, 3)
d = torch.ones(2, 5)

a

tensor([[[ 0.1470, -0.0082, -0.8585],
         [-0.9397, -0.3412,  2.3592]]])

In [8]:
a + b

tensor([[[1.1470, 0.9918, 0.1415],
         [0.0603, 0.6588, 3.3592]]])

In [9]:
a + c

tensor([[[1.1470, 0.9918, 0.1415],
         [0.0603, 0.6588, 3.3592]]])

In [10]:
a + d

RuntimeError: The size of tensor a (3) must match the size of tensor b (5) at non-singleton dimension 2

There is an important operation that we should know about: the matrix multiplication, represented by the `@` operator.

In [ ]:
a = torch.tensor([[1, 2, 3]])
b = torch.tensor([[4], [5], [6]])
print(a @ b)
print(b @ a)

tensor([[32]])
tensor([[ 4,  8, 12],
        [ 5, 10, 15],
        [ 6, 12, 18]])


Besides these functions, there are a bunch of useful ones 1-ary operators:

In [ ]:
a = torch.randn(10)
print(a)
print(a.sum())
print(a.mean())
print(a.relu())

tensor([ 1.0283,  0.2767,  0.4558,  2.0266, -0.1950, -0.1028,  1.2314, -1.7533,
        -0.0986, -0.3401])
tensor(2.5290)
tensor(0.2529)
tensor([1.0283, 0.2767, 0.4558, 2.0266, 0.0000, 0.0000, 1.2314, 0.0000, 0.0000,
        0.0000])


Part of the secret power of torch tensors is that all the operations happen at a very low memory-operation level that makes things really fast. Plus, you can use the `device` parameter to send the tensor to the GPU if available.